export const actionTypes = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    LOAD_PRODUCT: 'LOAD_PRODUCT',
    ADD_PRODUCT: 'ADD_PRODUCT',
    TOGGLE_BRAND: 'TOGGLE_BRAND',
    TOGGLE_STOCK: 'TOGGLE_STOCK'
}